kibot:
  version: 1

preflight:
  run_erc: true
  run_drc: true
  check_zone_fills: true

outputs:

  - name: ibom
    comment: 'HTML interactive BoM'
    type: ibom
    dir: BoM
    options:
      layer_view: F

  - name: 'print_sch'
    comment: "Schematic PDF"
    type: pdf_sch_print
    dir: Schematic

  - name: 'diff'
    comment: "Generate diff"
    type: diff
    dir: diff