kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false

outputs:

  # - name: ibom
  #   comment: 'HTML interactive BoM'
  #   type: ibom
  #   dir: BoM
  #   options:
  #     layer_view: F

  - name: 'print_sch'
    comment: "Schematic PDF"
    type: pdf_sch_print
    dir: Schematic

  - name: 'diff'
    comment: "Generate diff"
    type: diff
    dir: diff
    options:
      only_different: true
      always_fail_if_missing: true

  - name: 'render'
    comment: "Render 3D model"
    type: blender_export
    dir: render
    options:
      point_of_view:
        rotate_x: -30
        rotate_y: 0
        rotate_z: 30
