name: KiBot

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: Barklind/config.kibot.yaml
        dir: docs
        schema: 'Barklind/Barklind.kicad_sch'
        board: 'Barklind/Barklind.kicad_pcb'
    - name: Upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs